[book]
authors = ["Hector PENG, unisko # gmail.com"]
language = "zh"
multilingual = false
src = "src"
title = "Erlang 编程"
description = "Yet another Chinese Erlang book, Programming Erlang, 2nd Edition, Joe Armstrong"


[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]


[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/highlight.min.js", "theme/c.min.js", "theme/elixir.min.js", "theme/shell.min.js", "theme/erlang.min.js", "theme/pagetoc.js"]
git-repository-url = "https://github.com/gnu4cn/erlang-book"
git-repository-icon = "fa-github"

[output.html.print]
enable = false

[output.html.search]
enable = false
