test_search:
	rebar3 compile
	erl -pa ./_build/default/lib/sherlock/ebin -s sherlock_mails test_search -s init stop > LOG_test

test_build:
	rebar compile
	erl -pa ./_build/default/lib/sherlock/ebin -s sherlock_mails test_build -s init stop > LOG_build






